### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by maxemann96** [zimmer-m/NashFlowComputation#4]
Hey, thank you for your work. In order to be used properly in other projects I suggest you to add a license. You can use the GitHub service [choosealicense](https://choosealicense.com/) to get help.

I would suggest a [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) license. I'm not a lawyer, this suggestion can be used without any warranty.

**Comment by LeonSering** [comment]
Thanks for the suggestion. I added the MIT License.
